name: pygeobase_env
dependencies:
- alabaster=0.7.6=py27_0
- babel=2.1.1=py27_0
- curl=7.43.0=1
- docutils=0.12=py27_0
- funcsigs=0.4=py27_0
- hdf5=1.8.15.1=2
- jinja2=2.8=py27_0
- krb5=1.13.2=0
- libgfortran=1.0=0
- libnetcdf=4.3.3.1=1
- markupsafe=0.23=py27_0
- mock=1.3.0=py27_0
- netcdf4=1.2.2=np110py27_0
- numpy=1.10.2=py27_0
- numpydoc=0.5=py27_1
- openblas=0.2.14=3
- openssl=1.0.2f=0
- pandas=0.17.1=np110py27_0
- pbr=1.8.0=py27_0
- pip=8.0.2=py27_0
- py=1.4.31=py27_0
- pygments=2.0.2=py27_0
- pytest=2.8.5=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- readline=6.2=2
- setuptools=19.6.2=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - coverage==4.0.3
  - pygeogrids==0.1.5
  - pytest-cov==2.2.1
  - sphinx-rtd-theme==0.1.7

